#include<stdio.h>
int main()
{
    int n,arr[100],i,j,c=0,max=0;
    scanf("%d",&n);
    for(i=0;i<n;i++)
    {
        scanf("%d",&arr[i]);
    }
    for(i=0;i<n;i++)
    {
        if(arr[i]==1)
        {
            c=c+1;
        }
        if(arr[i]==0)
        {
            if(max<c)
            {
                max=c;
            }
            c=0;
        }
    }
    if(max<c)
    {
        max=c;
    }
    printf("%d",max);
}